name: AWS Key Expiry Reminder

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Runs every day at 9:00 UTC

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AWS Key Expiry Reminder
        run: python3 expiration_reminder_and_automation.py
